trigger:
- main/app

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHubRemeric'
        repository: 'remeric/board-game-selector'
        command: 'buildAndPush'
        Dockerfile: '**/app/Dockerfile'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'Ubuntu-latest'
    steps: 
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: '**/terraform/aws-ecs/'
        commandOptions: '-var application_version='$(tag)''
        allowTelemetryCollection: false

