trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         containerRegistry: 'DockerHubRemeric'
#         repository: 'remeric/board-game-selector'
#         command: 'buildAndPush'
#         Dockerfile: '**/app/Dockerfile'
#         tags: '$(tag)'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'Ubuntu-latest'
    steps: 
      - task: DownloadSecureFile@1
        name: publickey
        inputs:
          secureFile: 'default-ec2.pem'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            env
            export AWS_ACCESS_KEY_ID=$(client_id)
            export AWS_SECRET_ACCESS_KEY=$(client_secret)
            export AWS_DEFAULT_REGION
            env
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aws-ecs'
          commandOptions: '-backend-config="access_key=$(client_id)" -backend-config="secret_key=$(client_secret)" '
          backendType: 'selfConfigured'
          allowTelemetryCollection: true     
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            env

# -var ssh_public_key=$(publickey.securefilepath) 
