trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         containerRegistry: 'DockerHubRemeric'
#         repository: 'remeric/board-game-selector'
#         command: 'buildAndPush'
#         Dockerfile: '**/app/Dockerfile'
#         tags: '$(tag)'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'Ubuntu-latest'
    steps: 
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        displayName: install terraform
        inputs:
          terraformVersion: 'latest'

      - task: DownloadSecureFile@1
        name: publickey
        inputs:
          secureFile: 'default-ec2.pem'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            AWS_ACCESS_KEY_ID=$(client_id)
            AWS_SECRET_ACCESS_KEY=$(client_secret)

      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aws-ecs'
          backendType: 'selfConfigured'
          allowTelemetryCollection: true
      
    # - task: TerraformCLI@0
    #   inputs:
    #     command: 'apply'
    #     workingDirectory: '**/terraform/aws-ecs'
    #     commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.securefilepath) -var application_version=92'
    #     allowTelemetryCollection: false

